services:

    www.softwareshinobi.digital:

        container_name: www.softwareshinobi.digital

        image: softwareshinobi/www.softwareshinobi.digital

        restart: always

        build: 

            context: .

            dockerfile: Dockerfile

        environment:

          VIRTUAL_HOST: softwareshinobi.digital

          LETSENCRYPT_HOST: softwareshinobi.digital

        ports:

            - 8880:80
